@baseUrl = https://api-json-sever-demo.herokuapp.com/api
@resourceName=products
 
#Products
 
# @name getAll
GET {{baseUrl}}/{{resourceName}}
 
###
 
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?price_gte=400
 
###
 
# @name searchProducts
GET {{baseUrl}}/{{resourceName}}?name_like=fan
 
 
###
 
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=3
 
###
 
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc
 
 
###
 
# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json
 
{
   
    "categoryId": "7fcd39a3-bc42-4ff5-9f19-c2b2bdfae892",
    "name": "Gorgeous Granite Table",
    "color": "olive",
    "price": 400,
    "thumnailUrl": "http://placeimg.com/300/300"
}
 
###
 
# @name update
PATCH {{baseUrl}}/{{resourceName}}/kVByyeI
Content-Type: application/json
 
{
    "name": "Gorgeous Granite Table",
    "color": "RED",
    "price": 500
}
 
###
 
# @name remove
DELETE {{baseUrl}}/{{resourceName}}/5